version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "build"
    include: "scope"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "build"
    include: "scope"
