---
name: Main branch continuous integration and snapshots deployment
on:
  push:
    branches:
      - "main"

concurrency:
  group: "ci-cd-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    name: Deploy snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Test and deploy snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
        run: |
          VERSION=$(./mvnw -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' -pl :mutiny-project)
          if [[ ${VERSION} == *SNAPSHOT ]]; then
              echo "🚀 Run the tests"
              ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean verify
              echo "🚀 Deploy the snapshots"
              just -f .build/justfile-for-release -d . deploy-to-maven-central 
          else
              echo "🤌 This is a release commit, we won't do anything!"
          fi
